kind: pipeline
name: default

steps:
- name: install-dependencies
  image: node:7.2.1
  commands:
  # install unzip - used by tests/test-on-circle.sh
  - apt-get update
  - apt-get install -y unzip
  # Install yarn / yarn dependencies
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - yarn

- name: run-tests
  image: node:7.2.1
  environment:
    CIRCLE_NODE_INDEX: 0
    CIRCLE_NODE_TOTAL: 6
    CIRCLE_ARTIFACTS: /home/node
  commands:
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - export PATH="${PATH}:$(pwd)/node_modules/.bin"
  - echo $PATH
  - tests/test-on-circle.sh

trigger:
  event:
  - push
  - pull_request